# Generated by Django 3.2.7 on 2021-09-02 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название клуба')),
                ('country', models.CharField(choices=[('FR', 'France'), ('RU', 'Russia'), ('US', 'USA'), ('UK', 'United Kingdom'), ('RO', 'Romania')], max_length=50, verbose_name='Страна клуба')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('citizenship', models.CharField(choices=[('FR', 'France'), ('RU', 'Russia'), ('US', 'USA'), ('UK', 'United Kingdom'), ('RO', 'Romania')], max_length=50, verbose_name='Гражданство')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='club.club', verbose_name='Клуб')),
            ],
        ),
    ]
